# **ICT303 - Advanced Machine Learning and Artificial Intelligence**
# **Lab 1 - Introduction to Python, NumPy and Torch**

The purpose of this lab is to provide you with the Python toolkit you will be using in this unit. This includes:
- Familiarizing yourself with Python programming. Although there is no unit within the IT degree that explicitly teaches Python, as an IT student of Murdoch, you should by now have learned C, Java and C++. These are the foundations that will enable you to learn any other programming language by your own. In fact,  as an IT expert, you MUST learn how to learn by yourself.
- Familiarize yourself with some important Python libraries that we will be using during the semester. These include NumPy and PyTorch.

Note that, Section 2 of this lab has been adapted from https://numpy.org/doc/stable/user/quickstart.html. Sections 3 onwards have been adapted from https://deeplearning.cs.cmu.edu/F20/index.html.

### **1. Python**

In this unit, we will use the [*Colab research platform*](https://colab.research.google.com/) for programming. Since you are reading this, it means you have already created a Google account and managed to open this Colab notebook.

Note also that you can open this document using Jupiter Notebook.

Before you continue, I recommend to create a folder named ICT303 in your Google drive, and make sure you save all your work (i.e., the notebooks and associated files your will create as part of this unit) in it.

You can find more information on how to use Colab and its features in the link above.

Note also that Colab integrates cleanly with Github, allowing both loading notebooks from Github and saving notebooks into Github. You can find more details about this functionality here: https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb.

Once done, it is time for you to learn a little bit about Python. There are plenty of online resources that you can use. I recommend downloading this tutorial notebook from CMU: https://deeplearning.cs.cmu.edu/F20/document/recitation/Rec_0A_Fundamentals_of_Python.zip
- Download the notebook and then upload it to your google drive and view it in Colab.
- Work through the tutorial step by step.

Note that you do not need to do the entire Python tutorial. Scheme through it and try to:
- Understand the structure of a Python program
- How to create classes and methods (functions)
- How to pass in parameters into functions and return values in functions.

Then, use the tutorial as a reference whenever you need to create something with Python.


### **2. NumPy**

The first library of interest is [NumPy](http://www.numpy.org/). You can find more details about NumPy at https://numpy.org/doc/stable/user/quickstart.html.  You can also go through this CMU tutorial: https://deeplearning.cs.cmu.edu/F20/document/recitation/Rec_0B_Fundamentals_of_Numpy.zip

In this document, I will summarize some of the most important features of NumPy.

NumPy is the fundamental package for scientific computing with Python. It contains, among other things:

- A powerful N-dimensional array object that allows you to manipulate N-dimensional arrays,
- Sophisticated (broadcasting) functions. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number generation capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

#### **2.1. The Basics**

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy, dimensions are called **axes**.

NumPy arrays are called **ndarray** and are defined in the package **numpy.array**.

****Example 1 - A point or vector in 3D space:****
A point in 3D space has 3 coordinates (x, y, z). Similarly, a vector in 3D space has 3 coordinates (x, y, z). Thus, from the programming point of view, they can both be defined using an array of 3 elements. Using NumPy **ndarray**, they can be defined as an array that has one axis (one dimension). For example:

In [ ]:
## A point in 3D space
p = [1, 2, 1]

## A vector in 3D space
v = [3, 2.1, 5]

## printing
print("The point is: ")
print(p)
print("The vector is: ")
print(v)

The point is: 
[1, 2, 1]
The vector is: 
[3, 2.1, 5]


***Example 2 - A list of 3D points***

Assume that we would like to create a data structure that will hold a list of 3D points.  Using NumPy's **ndarray**, it can be defined using an array that has two axes:



In [2]:
import numpy as np
vertices =np.array([[1, 0, 0],
           [3, 2, 0.1],
           [-1.3, 2.4, 5],
           [5.3, 3, -2.3]])
# Printing - method 1
print(vertices)

# Printing - method 2
vertices

# Printing the first point or row (of index 0)
print(vertices[0,])

# Printing the first column (of index 0)
print(vertices[:,0])

[[ 1.   0.   0. ]
 [ 3.   2.   0.1]
 [-1.3  2.4  5. ]
 [ 5.3  3.  -2.3]]
[1. 0. 0.]
[ 1.   3.  -1.3  5.3]


This ndarray has two axes. The first axis has a length of 4 The number of rows). The second axis has a length of 3 (the number of columns).

The class ndarray has many important attributes. The most important ones include:

- ***ndarray.ndim*** - The number of axes (dimensions) of the array.

- ***ndarray.shape*** - the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with $n$ rows and $m$ columns, shape will be $(n,m)$. The length of the shape tuple is therefore the number of axes, ndim.

- ***ndarray.size*** - the total number of elements of the array. This is equal to the product of the elements of shape.

- ***ndarray.dtype*** - an object describing the type of the elements in the array. One can create or specify dtype using standard Python types. Additionally, NumPy provides types of its own: `numpy.int32`, `numpy.int16`, and `numpy.float64` are some examples.

- ***ndarray.itemsize*** - the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize equal to 8 (i.e., 64/8), while one of type complex32 has itemsize equal to 4 (i.e., 32/8). It is equivalent to `ndarray.dtype.itemsize`.

- ***ndarray.data*** - the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

***Example 3.***  Try these properties on the examples defined above.

#### **2.2. Creating and printing NumPy arrays**

Please refer to Sections ***Array Creation*** and ***Printing Arrays*** of https://numpy.org/doc/stable/user/quickstart.html

***Example 4***: Create a random 1D array of size $32$. Then try to:
- Reshape the 1D array into a 2D array of size $8 \times 4$ (i.e., axes 1 will have size $8$ while axes $2$ will have size $4$). Use the function numpy.arrange. For this, please refer to https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
- Display (print) the results.

As a bonus question, try to rearrange the 2D array into a 1D array. For this, check the different parameters of the function reshape, especially the last parameter which takes one of the three values: 'C', 'F', and 'A'. Please refer to https://numpy.org/doc/stable/reference/generated/numpy.reshape.html.

#### **2.3. Basic Operations**

You can do arithmetic operations (additions, subtractions, multiplications) on NumPy arrays. These will be applied element wise. For example, to add two arrays ***A*** and ****B***  of same dimension, you do not need to write a loop through its elements, you just need to write ***A+B***. Please refer to the section ***Basic Operations*** of https://numpy.org/doc/stable/user/quickstart.html.

It is important to pay attention to some aspects that are specific to NumPy arrays. In particular, the product operator *  operates elementwise in NumPy array. If you want to use matrix product, then you have to use the operator ***@*** (in Python > 3.5) or the ***dot*** function. Please refer to https://numpy.org/doc/stable/user/quickstart.html for more details.

The example below illustrates this concept.

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
C1 = A * B     # elementwise product

C2 = A @ B     # matrix product

C3 = A.dot(B)  # another matrix product

print (C1)
print (C2)
print (C3)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Note also that the NumPy array class provides methods such as `sum`, `min`, `max`, etc., which operate on the entire elements of the array. By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:



In [39]:
b = np.arange(12).reshape(6, 2)
print (b)                 # Printing b

a = b
a = a.reshape(3,4)
print (a)
print (b)
#print(b.sum(axis=0))     # sum of each column

#print(b.min(axis=1))     # min of each row

#print(b.cumsum(axis=1))  # cumulative sum along each row

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


NumPy also provides common mathematical functions such as `exp` (for exponential), `sqrt` (for square root), etc.





#### **2.4. Indexing, Slicing and Iterating**

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [ ]:
# An array of 10 elements with values [0, 1, , ..., 9] and make every element power 3
a = np.arange(10)
a

# First element
print("First element: ")
a[0]

# Last element
print("Last element: ")
a[-1]

# Print the 3rd element - Similar to C, array indices start from 0
print("3rd element: ")
a[2]

# Print the elements index between 2 to 5
print("Elements from 2 to 5: ")
a[2:5]

# From start to position 6, exclusive, set every 2nd element to 1000
# This is equivalent to a[0:6:2] = 1000;
a[:6:2] = 1000
a

# Reverse the array a, i.e., last element becomes first, etc.
a[::-1]

# Looping through the elements of a
for x in a:
    print(x)

**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas.

When fewer indices are provided than the number of axes, the missing indices are considered complete slices. For instance, in the example below, `b[1]` is the same as `b[1, :] `and is also the same as `b[1, ...`] where the three dots mean the remaining dimensions.

In [18]:
import numpy as np

b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(b[3,:2])

print(b[1,:])

print(b[1, ...])

[30 31]
[10 11 12 13]
[10 11 12 13]


**Iterating** over multidimensional arrays is done with respect to the first axis:

In [ ]:
for row in b:
    print(row)


In the example above, if `b` had three axes (dimensions) then row will have two dimensions.



#### **2.5. Shape manipulation**

The shape of an array is the number of elements it has along each axis. You can change this shape by
- flattening it (e.g., 2D array  becomes one long 1D array) using the method `ravel()`
- reshape it. For example, if you have an array of 3 rows and 4 columns,  you can reshape it into an array of 6 rows and 2 columns using the method `reshape()`.



#### **2.6. Other matters**

You can stack together several arrays along different axis to form a new array. You can also split one array into several smaller ones.

It also important to pay attention to how arrays are copied. Copying an array variabe into another variable can be done in different ways:
- A simple assignment `b = a` does not make a separate (new) copy of `a`. Instead, `b` becomes a new name for the same ndarray.
- Viewer or shallow copy using the view method which creates a new array that looks at the same data. Also, slicing an array returns a view of it.
- Deep copy using the method `copy()`.

Please refer to https://numpy.org/doc/stable/user/quickstart.html for more advanced topics related to NumPy arrays, including tricks and tips!

### **3. PyTorch**

The second library of interest is PyTorch, which is an open-source deep learning library (called also frameowrk) for python, and will be extensively used throughout this unit.

Note that PyTorch is not only deep learning framework that one can use. Other popular and commonly used frmeworks include TensorFlow, MXNet, PyTorch  Lightning, etc.

You can install PyTorch on your local machine by referring to https://PyTorch.org/get-started/locally/.

PyTorch is an open source deep learning platform that provides a seamless path from research prototyping to production deployment.
> - *Hybrid Front-End:* A new hybrid front-end seamlessly transitions between eager mode and graph mode to provide both flexibility and speed.
> - *Distributed Training:* Scalable distributed training and performance optimization in research and production is enabled by the torch.distributed backend.
> - *Python-First:* Deep integration into Python allows popular libraries and packages to be used for easily writing neural network layers in Python.
> - *Tools & Libraries:* A rich ecosystem of tools and libraries extends PyTorch and supports development in computer vision, NLP and more.
>
> To learn more about PyTorch and expand your knowledge, please refer to [About PyTorch](https://pytorch.org/)*

One consideration as to why we are using PyTorch is most succinctly summerized by Andrej Karpathy, Director of Artificial Intelligence and Autopilot Vision at Tesla. The technical summary can be found [here](https://twitter.com/karpathy/status/868178954032513024?lang=en).

To use PyTorch in colab, please refer to https://colab.research.google.com/github/omarsar/pytorch_notebooks/blob/master/pytorch_quick_start.ipynb.

You can use the code below to check whether PyTorch is properly installed and which version is installed.

In [54]:
## Checking that PyTorch is running

import torch

# Check the version
print(torch.__version__)



2.1.0+cu121


In [55]:
# Creare a simple Tensor
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

One of the fundamental concepts in PyTorch is the **Tensor**, a multi-dimensional matrix containing elements of a single type. Tensors are similar to numpy nd-arrays and tensors support most of the functionality that numpy matrices do.

Please go through this guide: https://pytorch.org/tutorials/ to learn about PyTorch, from the basics to advanced topics. Many of the examples are about deep learning - don't worry about them at this stage. Below are the topics that you need to familiarize yourself with at this stage.

Start by familiarizing yourself with ***the basics*** at: https://pytorch.org/tutorials/beginner/basics/intro.html. You should learn about:
- **Tensors:** These are a specialized data structure, very similar to arrays and matrices. Tensors in PyTorch are used to encode inputs and outputs of a model (neural network), as well as the model's parameters. They are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators.  In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.
- **Datasets and DataLoaders:** PyTorch offers ready-to-use classes and functions for loading standard datasets used to train neural networks.

The Quick Start section of the tutorial above provides a quick overview of the functionalities available

Once we advance in the unit and you learn about neural networks, then you need to familiarize yourself with the following topics:
- **Transforms:** i.e., how to transform the data to make it suitable for training neural neytworks.
- **Build model:** to build neural network models.
- **Automatic differentiation:** I will talk about this later in the lecture.
- **Optimization loop:** I will talk about this later in the lecture.

This week, make sure that you familiarize yourself with **Tensors**. You need to know:
- How to create tensors directly from data, from another NumPy array, and from another Tensor.
- Attributes of a Tensor.
- Operations on Tensors, including indexing and slicing.

### **4. Practice what you learned**

In the following exercises, you will familiarize yourself with tensors and more importantly, the PyTorch documentation. It is important to note that for this section, we are simply using PyTorch’s tensors as a matrix library, just like numpy. So please do not use functions in `torch.nn` such as `torch.nn.ReLU`.

In PyTorch, it is very simple to convert between numpy arrays and tensors. PyTorch’s tensor library provides functions to perform the conversion in either direction.

#### **4.1. Converting from NumPy to PyTorch Tensor**
In this task, you will implement a conversion function from arrays to tensors.

The function should take a numpy ndarray and convert it to a PyTorch tensor.

*Function torch.tensor is one of the simple ways to implement it.*

**Your Task**: Implement the function `numpy2tensor`.

In [ ]:
def numpy2tensor(x):
    conv = torch.tensor(x)

    return conv

**Test Example:**

In [ ]:
X = np.random.randint(-1000, 1000, size=3000)

print(type(numpy2tensor(X)))

<class 'torch.Tensor'>


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> type(numpy2tensor(X)) </b></tt></td>
        <td style="text-align:left;"><tt> &lt;class &#39;torch.Tensor&#39;&gt; </tt></td>
    </tr>
</table>

#### **4.2. Converting from PyTorch Tensor to NumPy**

In this task, you will implement a conversion function from tensors to arrays.

The function should take a PyTorch tensor and convert it to a numpy ndarray.

**Your Task**: Implement the function `tensor2numpy`.

In [ ]:
def tensor2numpy(x):
    conv = x.numpy()

    return conv

**Test Example:**

In [ ]:
X = np.random.randint(-1000, 1000, size=3000)
X = torch.from_numpy(X)

print(type(tensor2numpy(X)))

<class 'numpy.ndarray'>


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> type(tensor2numpy(X)) </b></tt></td>
        <td style="text-align:left;"><tt> &lt;class &#39;numpy.ndarray&#39;&gt; </tt></td>
    </tr>
</table>

### **5. Vectorization**

Lists are a foundational data structure in Python, allowing us to create simple and complex algorithms to solve problems. However, in mathematics and particularly in linear algebra, we work with vectors and matrices to model problems and create statistical solutions. Through these exercises, we will begin introducing you to how to think more mathematically through the use of NumPy by starting with a process known as vectorization.

Index chasing is a very valuable skill, and certainly one you will need in this course, but mathematical problems often have simpler and more efficient representations that use vectors. The process of converting from an implementation that uses indices to one that uses vectors is known as **vectorization**. Once vectorized, the resulting implementation often yields to a faster and more readable code than before.

In the following problems, we will ask you to practice reading mathematical expressions and deduce their vectorized equivalent along with their implementation in Python. You will use the NumPy array object as the Python equivalent to a vector, and in latter sections you will work with sets of vectors known as matrices.

For the following tasks, you will be asked to complete the same task first using **NumPy** operations, then again using **PyTorch** operations.

#### **5.1. Dot Product**

In this task, you will implement the dot product function for numpy arrays and pytorch tensors.

The dot product (also known as the scalar product or inner product) is the linear combination of the $n$ real components of two vectors $\textbf{x} = (x_1,x_2, ...)^T$ and $\textbf{y}=(y_1, y_2, ...)^T$.

$$\textbf{x} \cdot \textbf{y} = x_1 y_1 + x_2 y_2 + \cdots + x_n y_n$$

**Your Task**: Implement the functions `NUMPY_dot` & `PYTORCH_dot`.

In [46]:
def EXAMPLE_inefficient_dot(x, y):
    """
    Inefficient dot product of two arrays.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    assert(len(x) == len(y))

    result = 0
    for i in range(len(x)):
        result += x[i]*y[i]

    return result

In [59]:
def NUMPY_dot(x, y):
    """
    Dot product of two arrays.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """



    return x @ y

In [52]:
def PYTORCH_dot(x, y):
    """
    Dot product of two tensors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """

    return x @ y

**Test Example:**

In [60]:
import numpy as np
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

print(NUMPY_dot(X,Y))

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(PYTORCH_dot(X,Y))

7082791
tensor(7082791)


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_dot(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 7082791 </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_dot(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 7082791 </tt></td>
    </tr>
</table>

#### **5.2. Outer Product**

In this task, you will implement the outer product function for numpy arrays & torch tensors.

The outer product (also known as the tensor product) of vectors $\textbf{x}$ and $\textbf{y}$ is defined as

$$
\textbf{x} \otimes \textbf{y} =
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
$$

**Your Task**: Implement the functions `NUMPY_outer` & `PYTORCH_outer`.


In [65]:
def EXAMPLE_inefficient_outer(x, y):
    """
    Inefficiently compute the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    result = np.zeros((len(x), len(y)))
    for i in range(len(x)):
        for j in range(len(y)):
            result[i, j] = x[i]*y[j]

    return result

In [66]:
def NUMPY_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    return np.outer(x,y)

In [82]:
def PYTORCH_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    return torch.outer(x, y)

**Test Example:**

In [83]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)


print(NUMPY_outer(X,Y))
#EXAMPLE_inefficient_outer(X, Y)

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)

print(PYTORCH_outer(X,Y))

[[  59092 -144096  136512 ...  -53088  -86268   53404]
 [  82467 -201096  190512 ...  -74088 -120393   74529]
 [-122111  297768 -282096 ...  109704  178269 -110357]
 ...
 [-144551  352488 -333936 ...  129864  211029 -130637]
 [-179707  438216 -415152 ...  161448  262353 -162409]
 [  88825 -216600  205200 ...  -79800 -129675   80275]]
tensor([[  59092, -144096,  136512,  ...,  -53088,  -86268,   53404],
        [  82467, -201096,  190512,  ...,  -74088, -120393,   74529],
        [-122111,  297768, -282096,  ...,  109704,  178269, -110357],
        ...,
        [-144551,  352488, -333936,  ...,  129864,  211029, -130637],
        [-179707,  438216, -415152,  ...,  161448,  262353, -162409],
        [  88825, -216600,  205200,  ...,  -79800, -129675,   80275]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_outer(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;59092&nbsp;-144096&nbsp;&nbsp;136512&nbsp;...&nbsp;&nbsp;-53088&nbsp;&nbsp;-86268&nbsp;&nbsp;&nbsp;53404] <br>
            &nbsp;[&nbsp;&nbsp;82467&nbsp;-201096&nbsp;&nbsp;190512&nbsp;...&nbsp;&nbsp;-74088&nbsp;-120393&nbsp;&nbsp;&nbsp;74529] <br>
            &nbsp;[-122111&nbsp;&nbsp;297768&nbsp;-282096&nbsp;...&nbsp;&nbsp;109704&nbsp;&nbsp;178269&nbsp;-110357] <br>
            &nbsp;... <br>
            &nbsp;[-144551&nbsp;&nbsp;352488&nbsp;-333936&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;211029&nbsp;-130637] <br>
            &nbsp;[-179707&nbsp;&nbsp;438216&nbsp;-415152&nbsp;...&nbsp;&nbsp;161448&nbsp;&nbsp;262353&nbsp;-162409] <br>
            &nbsp;[&nbsp;&nbsp;88825&nbsp;-216600&nbsp;&nbsp;205200&nbsp;...&nbsp;&nbsp;-79800&nbsp;-129675&nbsp;&nbsp;&nbsp;80275]] <br>
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_outer(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;59092&nbsp;-144096&nbsp;&nbsp;136512&nbsp;...&nbsp;&nbsp;-53088&nbsp;&nbsp;-86268&nbsp;&nbsp;&nbsp;53404] <br>
            &nbsp;[&nbsp;&nbsp;82467&nbsp;-201096&nbsp;&nbsp;190512&nbsp;...&nbsp;&nbsp;-74088&nbsp;-120393&nbsp;&nbsp;&nbsp;74529] <br>
            &nbsp;[-122111&nbsp;&nbsp;297768&nbsp;-282096&nbsp;...&nbsp;&nbsp;109704&nbsp;&nbsp;178269&nbsp;-110357] <br>
            &nbsp;... <br>
            &nbsp;[-144551&nbsp;&nbsp;352488&nbsp;-333936&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;211029&nbsp;-130637] <br>
            &nbsp;[-179707&nbsp;&nbsp;438216&nbsp;-415152&nbsp;...&nbsp;&nbsp;161448&nbsp;&nbsp;262353&nbsp;-162409] <br>
            &nbsp;[&nbsp;&nbsp;88825&nbsp;-216600&nbsp;&nbsp;205200&nbsp;...&nbsp;&nbsp;-79800&nbsp;-129675&nbsp;&nbsp;&nbsp;80275]] <br>
        </tt></td>
    </tr>
</table>

#### **5.3. Hadamard Product**

In this task, you will implement the Hadamard product function, `multiply`, for numpy arrays & torch tensors.

The Hadamard product (also known as the Schur product or entrywise product) of vectors $\textbf{x}$ and $\textbf{y}$ is defined as

$$
\textbf{x} \circ \textbf{y} =
\begin{bmatrix}
x_{1} y_{1} & x_{2} y_{2} & … & x_{n} y_{n}
\end{bmatrix}
$$

**Your Task**: Implement the functions `NUMPY_multiply` & `PYTORCH_multiply`.

In [61]:
def EXAMPLE_inefficient_multiply(x, y):
    """
    Inefficiently multiply arguments element-wise.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """
    assert(len(x) == len(y))

    result = np.zeros(len(x))
    for i in range(len(x)):
        result[i] = x[i]*y[i]

    return result

In [76]:
def NUMPY_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """

    return x * y

In [77]:
def PYTORCH_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """

    return x * y

**Test Example:**

In [78]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

print(NUMPY_multiply(X,Y))

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(PYTORCH_multiply(X,Y))

[  59092 -201096 -282096 ...  129864  262353   80275]
tensor([  59092, -201096, -282096,  ...,  129864,  262353,   80275])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_multiply(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [&nbsp;&nbsp;59092&nbsp;-201096&nbsp;-282096&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;262353&nbsp;&nbsp;&nbsp;80275]
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_multiply(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [&nbsp;&nbsp;59092&nbsp;-201096&nbsp;-282096&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;262353&nbsp;&nbsp;&nbsp;80275]
        </tt></td>
    </tr>
</table>

#### **5.4. Sum-Product**
In this task, you will implement the sum-product function for numpy arrays & torch tensors.

The sum-product of vectors $\textbf{x}$ and $\textbf{y}$, each with n real component, is defined as

$$
f(\textbf{x}, \textbf{y}) =
{
\begin{bmatrix}
1\\
1\\
⋮\\
1
\end{bmatrix}^{\;T}
%
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
%
\begin{bmatrix}
1\\
1\\
⋮\\
1
\end{bmatrix}
} =
\displaystyle\sum_{i=1}^{n} \displaystyle\sum_{j=1}^{n} x_i \cdot y_j
$$

**Your Task**: Implement the functions `NUMPY_sumproduct` & `PYTORCH_sumproduct`.


In [ ]:
def EXAMPLE_inefficient_sumproduct(x, y):
    """
    Inefficiently sum over all the dimensions of the outer product
    of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    assert(len(x) == len(y))

    result = 0
    for i in range(len(x)):
        for j in range(len(y)):
            result += x[i] * y[j]

    return result

In [90]:
def NUMPY_sumproduct(x, y):
    """
    Sum over all the dimensions of the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    result = np.outer(x,y)
    result = np.sum(result)

    return result

In [91]:
def PYTORCH_sumproduct(x, y):
    """
    Sum over all the dimensions of the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """
    result = torch.outer(x,y)
    result = torch.sum(result)

    return result

**Test Example:**

In [92]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

print(NUMPY_sumproduct(X,Y))

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(PYTORCH_sumproduct(X,Y))

265421520
tensor(265421520)


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_sumproduct(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 265421520 </tt></td>
        <td style="text-align:left;"><tt><b> TORCH_sumproduct(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 265421520 </tt></td>
    </tr>
</table>

#### **5.5. ReLU**

In this task, you will implement the ReLU activation function for numpy arrays and torch tensors.

The ReLU activation (also known as the rectifier or rectified linear unit)  function takes as input  a matrix $X = (x_{ij}$ and returns another metric $Z$ such that:

$$Z = {\tt ReLU}(X) \implies \begin{cases}z_{ij} = x_{ij}&{\mbox{if }}x_{ij}>0\\z_{ij} = 0&{\mbox{otherwise.}}\end{cases}$$

The notation $X = (x_{ij})$   indicates that $X$ is a 2D matrix whose elements are  $x_{ij}$.

**Your Task:** Implement the functions `NUMPY_ReLU` & `PYTORCH_ReLU`.

In [ ]:
def EXAMPLE_inefficient_ReLU(x):
    """
    Inefficiently applies the rectified linear unit function
    element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    result = np.copy(x)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i][j] < 0:
                result[i][j] = 0

    return result

In [94]:
def NUMPY_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    return np.maximum(x, 0)

In [97]:
def PYTORCH_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    return torch.relu(x)

**Test Example:**

In [98]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

print(NUMPY_ReLU(X))

X = torch.from_numpy(X)
print(PYTORCH_ReLU(X))

[[  0   0 653 ... 773 961   0]
 [  0 456   0 ... 168 273   0]
 [936 475   0 ... 408   0   0]
 ...
 [  0 396 457 ... 646   0   0]
 [645 943   0 ... 863   0 790]
 [641   0 379 ... 347   0   0]]
tensor([[  0,   0, 653,  ..., 773, 961,   0],
        [  0, 456,   0,  ..., 168, 273,   0],
        [936, 475,   0,  ..., 408,   0,   0],
        ...,
        [  0, 396, 457,  ..., 646,   0,   0],
        [645, 943,   0,  ..., 863,   0, 790],
        [641,   0, 379,  ..., 347,   0,   0]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_ReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;653&nbsp;...&nbsp;773&nbsp;961&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;456&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;168&nbsp;273&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[936&nbsp;475&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;408&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;396&nbsp;457&nbsp;...&nbsp;646&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[645&nbsp;943&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;863&nbsp;&nbsp;&nbsp;0&nbsp;790] <br>
&nbsp;[641&nbsp;&nbsp;&nbsp;0&nbsp;379&nbsp;...&nbsp;347&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0]]
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_ReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;653&nbsp;...&nbsp;773&nbsp;961&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;456&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;168&nbsp;273&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[936&nbsp;475&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;408&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;396&nbsp;457&nbsp;...&nbsp;646&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[645&nbsp;943&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;863&nbsp;&nbsp;&nbsp;0&nbsp;790] <br>
&nbsp;[641&nbsp;&nbsp;&nbsp;0&nbsp;379&nbsp;...&nbsp;347&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0]]
        </tt></td>
    </tr>
</table>

#### **5.6. Prime ReLU (derivative of ReLU)**

In this task, you will implement the derivative of the ReLU activation function for numpy arrays and torch tensors.

The derivative of the ReLU activation matrix $Z$ resulting from applying the derivative of the ReLU function to matrix $X$ is defined such that for $X,Z \in M_{m \times n} (\mathbb{R})$,

$$Z = {\tt PrimeReLU}(X) \implies \begin{cases}z_{ij} = \frac{d}{dx_{ij}} (x_{ij}) = 1&{\mbox{if }}x_{ij}> 0\\z_{ij} = \frac{d}{dx_{ij}} (0)=0&{\mbox{otherwise.}}\end{cases}$$


**Your Task:** Implement the functions `NUMPY_PrimeReLU` & `PYTORCH_PrimeReLU`.

In [ ]:
def EXAMPLE_inefficient_PrimeReLU(x):
    """
    Inefficiently applies the derivative of the rectified linear unit
    function element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    result = np.copy(x)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i][j] <= 0:
                result[i][j] = 0
            else:
                result[i][j] = 1

    return result

In [99]:
def NUMPY_PrimeReLU(x):
    """
    Applies the derivative of the rectified linear unit function
    element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    return np.where(x > 0, 1, 0)

In [101]:
def PYTORCH_PrimeReLU(x):
    """
    Applies derivative of the rectified linear unit function
    element-wise.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    return torch.where(x > 0, 1, 0)

**Test Example:**

In [102]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

print(NUMPY_PrimeReLU(X))

X = torch.from_numpy(X)
print(PYTORCH_PrimeReLU(X))

[[0 0 1 ... 1 1 0]
 [0 1 0 ... 1 1 0]
 [1 1 0 ... 1 0 0]
 ...
 [0 1 1 ... 1 0 0]
 [1 1 0 ... 1 0 1]
 [1 0 1 ... 1 0 0]]
tensor([[0, 0, 1,  ..., 1, 1, 0],
        [0, 1, 0,  ..., 1, 1, 0],
        [1, 1, 0,  ..., 1, 0, 0],
        ...,
        [0, 1, 1,  ..., 1, 0, 0],
        [1, 1, 0,  ..., 1, 0, 1],
        [1, 0, 1,  ..., 1, 0, 0]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_PrimeReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[0&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[0&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[0&nbsp;1&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;1] <br>
&nbsp;[1&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0]]
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_PrimeReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[0&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[0&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[0&nbsp;1&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;1] <br>
&nbsp;[1&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0]]
        </tt></td>
    </tr>
</table>